# Automatically merge PR from dependabot

name: "Automerge"
on:
  # Automatically trigger it there are changes in repo
  pull_request:
    branches: [ 'main' ]

  # Allow manually trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Install Dependencies'
        run: |
          echo command to prepare env and pull dependencies
      - name: Run tests
        run: |
          echo command to run tests

  Automerge:
    runs-on: ubuntu-latest
    needs: [ Test ]
    steps:
      - name: 'Merge PR'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (!context.payload.pull_request) {
              console.log('Not Merged 🚫');
              console.log('No pull_request found in payload.');
              return;
            }
            console.log(`Merging PR <${context.payload.pull_request.number}>... 🕜`);
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            if (pr.data.user.login !== 'dependabot[bot]') {
              console.log('Not Merged 🚫');
              console.log(`User <${pr.data.user.login}> does not equal <dependabot[bot]>`);
            } else {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
              });
              console.log('Merged 🎉');
            }
